version: 0.0
os: linux
files:
  - source: /k8s
    destination: /opt/codedeploy/k8s
  - source: /scripts
    destination: /opt/codedeploy/scripts
permissions:
  - object: /opt/codedeploy
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
